// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const addCollection = `-- name: AddCollection :execrows
INSERT INTO collections (user_id, post_id, folder_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, post_id) DO NOTHING
`

type AddCollectionParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	PostID   uuid.UUID  `json:"post_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) AddCollection(ctx context.Context, arg AddCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addCollection, arg.UserID, arg.PostID, arg.FolderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCollectionFolderPosts = `-- name: CountCollectionFolderPosts :one
SELECT COUNT(*)::bigint
FROM collections
WHERE user_id = $1 AND folder_id = $2
`

type CountCollectionFolderPostsParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) CountCollectionFolderPosts(ctx context.Context, arg CountCollectionFolderPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionFolderPosts, arg.UserID, arg.FolderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCollectionFolders = `-- name: CountCollectionFolders :one
SELECT COUNT(*)::bigint FROM collection_folders WHERE user_id = $1
`

func (q *Queries) CountCollectionFolders(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionFolders, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCollections = `-- name: CountCollections :one
SELECT COUNT(*)::bigint FROM collections WHERE user_id = $1
`

func (q *Queries) CountCollections(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCollections, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCollectionFolder = `-- name: CreateCollectionFolder :one
INSERT INTO collection_folders (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateCollectionFolderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateCollectionFolder(ctx context.Context, arg CreateCollectionFolderParams) (CollectionFolder, error) {
	row := q.db.QueryRow(ctx, createCollectionFolder, arg.ID, arg.UserID, arg.Name)
	var i CollectionFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollectionFolder = `-- name: DeleteCollectionFolder :execrows
DELETE FROM collection_folders WHERE id = $1 AND user_id = $2
`

type DeleteCollectionFolderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCollectionFolder(ctx context.Context, arg DeleteCollectionFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollectionFolder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCollectionFolderByID = `-- name: GetCollectionFolderByID :one
SELECT id, user_id, name, created_at, updated_at FROM collection_folders
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCollectionFolderByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCollectionFolderByID(ctx context.Context, arg GetCollectionFolderByIDParams) (CollectionFolder, error) {
	row := q.db.QueryRow(ctx, getCollectionFolderByID, arg.ID, arg.UserID)
	var i CollectionFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCollected = `-- name: IsCollected :one
SELECT EXISTS(
    SELECT 1 FROM collections
    WHERE user_id = $1 AND post_id = $2
) AS collected
`

type IsCollectedParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) IsCollected(ctx context.Context, arg IsCollectedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCollected, arg.UserID, arg.PostID)
	var collected bool
	err := row.Scan(&collected)
	return collected, err
}

const listCollectionFolderPosts = `-- name: ListCollectionFolderPosts :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key,
    COALESCE(pm.width, 0) AS width,
    COALESCE(pm.height, 0) AS height,
    c.created_at AS collected_at
FROM collections c
JOIN posts p ON p.id = c.post_id
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key, width, height
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
WHERE c.user_id = $1 AND c.folder_id = $2
ORDER BY c.created_at DESC, c.post_id DESC
LIMIT $4 OFFSET $3
`

type ListCollectionFolderPostsParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FolderID    *uuid.UUID `json:"folder_id"`
	OffsetCount int32      `json:"offset_count"`
	LimitCount  int32      `json:"limit_count"`
}

type ListCollectionFolderPostsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
	Width          int32       `json:"width"`
	Height         int32       `json:"height"`
	CollectedAt    time.Time   `json:"collected_at"`
}

func (q *Queries) ListCollectionFolderPosts(ctx context.Context, arg ListCollectionFolderPostsParams) ([]ListCollectionFolderPostsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionFolderPosts,
		arg.UserID,
		arg.FolderID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionFolderPostsRow{}
	for rows.Next() {
		var i ListCollectionFolderPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
			&i.Width,
			&i.Height,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionFolders = `-- name: ListCollectionFolders :many
SELECT id, user_id, name, created_at, updated_at FROM collection_folders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListCollectionFoldersParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

func (q *Queries) ListCollectionFolders(ctx context.Context, arg ListCollectionFoldersParams) ([]CollectionFolder, error) {
	rows, err := q.db.Query(ctx, listCollectionFolders, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionFolder{}
	for rows.Next() {
		var i CollectionFolder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key,
    COALESCE(pm.width, 0) AS width,
    COALESCE(pm.height, 0) AS height,
    c.created_at AS collected_at
FROM collections c
JOIN posts p ON p.id = c.post_id
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key, width, height FROM post_media
    WHERE post_id = p.id ORDER BY sort_order ASC LIMIT 1
) pm ON true
WHERE c.user_id = $1
ORDER BY c.created_at DESC, c.post_id DESC
LIMIT $3 OFFSET $2
`

type ListCollectionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListCollectionsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
	Width          int32       `json:"width"`
	Height         int32       `json:"height"`
	CollectedAt    time.Time   `json:"collected_at"`
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
			&i.Width,
			&i.Height,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollection = `-- name: RemoveCollection :execrows
DELETE FROM collections
WHERE user_id = $1 AND post_id = $2
`

type RemoveCollectionParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) RemoveCollection(ctx context.Context, arg RemoveCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCollection, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCollectionFolder = `-- name: UpdateCollectionFolder :one
UPDATE collection_folders
SET name = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateCollectionFolderParams struct {
	Name   string    `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCollectionFolder(ctx context.Context, arg UpdateCollectionFolderParams) (CollectionFolder, error) {
	row := q.db.QueryRow(ctx, updateCollectionFolder, arg.Name, arg.ID, arg.UserID)
	var i CollectionFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
