// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPostID = `-- name: CountCommentsByPostID :one
SELECT COUNT(*)::bigint FROM comments WHERE post_id = $1
`

func (q *Queries) CountCommentsByPostID(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPostID, postID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    id, post_id, user_id, parent_id, content
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, post_id, user_id, parent_id, content, like_count, created_at
`

type CreateCommentParams struct {
	ID       uuid.UUID  `json:"id"`
	PostID   uuid.UUID  `json:"post_id"`
	UserID   uuid.UUID  `json:"user_id"`
	ParentID *uuid.UUID `json:"parent_id"`
	Content  string     `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const decrementCommentLikeCount = `-- name: DecrementCommentLikeCount :exec
UPDATE comments SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementCommentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementCommentLikeCount, id)
	return err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, user_id, parent_id, content, like_count, created_at FROM comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementCommentLikeCount = `-- name: IncrementCommentLikeCount :exec
UPDATE comments SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementCommentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCommentLikeCount, id)
	return err
}

const listCommentsByPostID = `-- name: ListCommentsByPostID :many
SELECT
    c.id, c.post_id, c.user_id, c.parent_id, c.content, c.like_count, c.created_at,
    u.username AS author_username, u.avatar_url AS author_avatar
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.post_id = $1
ORDER BY c.created_at ASC, c.id ASC
LIMIT $3 OFFSET $2
`

type ListCommentsByPostIDParams struct {
	PostID      uuid.UUID `json:"post_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListCommentsByPostIDRow struct {
	ID             uuid.UUID   `json:"id"`
	PostID         uuid.UUID   `json:"post_id"`
	UserID         uuid.UUID   `json:"user_id"`
	ParentID       *uuid.UUID  `json:"parent_id"`
	Content        string      `json:"content"`
	LikeCount      int32       `json:"like_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
}

func (q *Queries) ListCommentsByPostID(ctx context.Context, arg ListCommentsByPostIDParams) ([]ListCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPostID, arg.PostID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByPostIDRow{}
	for rows.Next() {
		var i ListCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
