// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreatePostMedia implements pgx.CopyFromSource.
type iteratorForCreatePostMedia struct {
	rows                 []CreatePostMediaParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePostMedia) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePostMedia) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].PostID,
		r.rows[0].MediaKey,
		r.rows[0].MediaType,
		r.rows[0].Width,
		r.rows[0].Height,
		r.rows[0].SortOrder,
	}, nil
}

func (r iteratorForCreatePostMedia) Err() error {
	return nil
}

func (q *Queries) CreatePostMedia(ctx context.Context, arg []CreatePostMediaParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"post_media"}, []string{"id", "post_id", "media_key", "media_type", "width", "height", "sort_order"}, &iteratorForCreatePostMedia{rows: arg})
}
