// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTag = `-- name: AddPostTag :execrows
INSERT INTO post_tags (post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (post_id, tag_id) DO NOTHING
`

type AddPostTagParams struct {
	PostID uuid.UUID `json:"post_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addSearchHistory = `-- name: AddSearchHistory :exec
INSERT INTO search_history (user_id, keyword)
VALUES ($1, $2)
ON CONFLICT (user_id, keyword)
DO UPDATE SET searched_at = NOW()
`

type AddSearchHistoryParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Keyword string    `json:"keyword"`
}

func (q *Queries) AddSearchHistory(ctx context.Context, arg AddSearchHistoryParams) error {
	_, err := q.db.Exec(ctx, addSearchHistory, arg.UserID, arg.Keyword)
	return err
}

const countRecommendedPosts = `-- name: CountRecommendedPosts :one
SELECT COUNT(*)::bigint FROM posts
`

func (q *Queries) CountRecommendedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendedPosts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchHistory = `-- name: CountSearchHistory :one
SELECT COUNT(*)::bigint FROM search_history WHERE user_id = $1
`

func (q *Queries) CountSearchHistory(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchHistory, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchPosts = `-- name: CountSearchPosts :one
SELECT COUNT(*)::bigint
FROM posts
WHERE to_tsvector('simple', title || ' ' || content)
      @@ plainto_tsquery('simple', $1)
`

func (q *Queries) CountSearchPosts(ctx context.Context, searchQuery string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchPosts, searchQuery)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchTags = `-- name: CountSearchTags :one
SELECT COUNT(*)::bigint
FROM tags
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountSearchTags(ctx context.Context, searchQuery pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchTags, searchQuery)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*)::bigint
FROM users
WHERE username ILIKE '%' || $1 || '%'
`

func (q *Queries) CountSearchUsers(ctx context.Context, searchQuery pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, searchQuery)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTagPosts = `-- name: CountTagPosts :one
SELECT COUNT(*)::bigint
FROM post_tags
WHERE tag_id = $1
`

func (q *Queries) CountTagPosts(ctx context.Context, tagID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTagPosts, tagID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTopicPosts = `-- name: CountTopicPosts :one
SELECT COUNT(*)::bigint
FROM topic_posts
WHERE topic_id = $1
`

func (q *Queries) CountTopicPosts(ctx context.Context, topicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTopicPosts, topicID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTopics = `-- name: CountTopics :one
SELECT COUNT(*)::bigint FROM topics
`

func (q *Queries) CountTopics(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTopics)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTrendingSearches = `-- name: CountTrendingSearches :one
SELECT COUNT(*)::bigint FROM search_terms
`

func (q *Queries) CountTrendingSearches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrendingSearches)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, description, created_at
`

type CreateTagParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.Name, arg.Description)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deletePostTags = `-- name: DeletePostTags :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) DeletePostTags(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostTags, postID)
	return err
}

const deleteSearchHistory = `-- name: DeleteSearchHistory :exec
DELETE FROM search_history WHERE user_id = $1
`

func (q *Queries) DeleteSearchHistory(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSearchHistory, userID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, description, created_at FROM tags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, created_at FROM tags WHERE name = $1 LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, description, cover_url, created_at, updated_at FROM topics WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverURL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecommendedPosts = `-- name: ListRecommendedPosts :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
ORDER BY (
    p.like_count * 3 + p.collect_count * 4 + p.comment_count * 2 + p.view_count
) DESC, p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $1
`

type ListRecommendedPostsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

type ListRecommendedPostsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
}

func (q *Queries) ListRecommendedPosts(ctx context.Context, arg ListRecommendedPostsParams) ([]ListRecommendedPostsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendedPosts, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendedPostsRow{}
	for rows.Next() {
		var i ListRecommendedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchHistory = `-- name: ListSearchHistory :many
SELECT keyword, searched_at
FROM search_history
WHERE user_id = $1
ORDER BY searched_at DESC, keyword ASC
LIMIT $3 OFFSET $2
`

type ListSearchHistoryParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListSearchHistoryRow struct {
	Keyword    string    `json:"keyword"`
	SearchedAt time.Time `json:"searched_at"`
}

func (q *Queries) ListSearchHistory(ctx context.Context, arg ListSearchHistoryParams) ([]ListSearchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSearchHistory, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchHistoryRow{}
	for rows.Next() {
		var i ListSearchHistoryRow
		if err := rows.Scan(&i.Keyword, &i.SearchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagPosts = `-- name: ListTagPosts :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key
FROM post_tags pt
JOIN posts p ON p.id = pt.post_id
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
WHERE pt.tag_id = $1
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3 OFFSET $2
`

type ListTagPostsParams struct {
	TagID       uuid.UUID `json:"tag_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListTagPostsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
}

func (q *Queries) ListTagPosts(ctx context.Context, arg ListTagPostsParams) ([]ListTagPostsRow, error) {
	rows, err := q.db.Query(ctx, listTagPosts, arg.TagID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagPostsRow{}
	for rows.Next() {
		var i ListTagPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByPostID = `-- name: ListTagsByPostID :many
SELECT t.id, t.name, t.description, t.created_at
FROM post_tags pt
JOIN tags t ON t.id = pt.tag_id
WHERE pt.post_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByPostID(ctx context.Context, postID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicPosts = `-- name: ListTopicPosts :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key
FROM topic_posts tp
JOIN posts p ON p.id = tp.post_id
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
WHERE tp.topic_id = $1
ORDER BY tp.created_at DESC, tp.post_id DESC
LIMIT $3 OFFSET $2
`

type ListTopicPostsParams struct {
	TopicID     uuid.UUID `json:"topic_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListTopicPostsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
}

func (q *Queries) ListTopicPosts(ctx context.Context, arg ListTopicPostsParams) ([]ListTopicPostsRow, error) {
	rows, err := q.db.Query(ctx, listTopicPosts, arg.TopicID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicPostsRow{}
	for rows.Next() {
		var i ListTopicPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, description, cover_url, created_at, updated_at FROM topics
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListTopicsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverURL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingSearches = `-- name: ListTrendingSearches :many
SELECT keyword, search_count
FROM search_terms
ORDER BY search_count DESC, last_searched_at DESC, keyword ASC
LIMIT $2 OFFSET $1
`

type ListTrendingSearchesParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

type ListTrendingSearchesRow struct {
	Keyword     string `json:"keyword"`
	SearchCount int64  `json:"search_count"`
}

func (q *Queries) ListTrendingSearches(ctx context.Context, arg ListTrendingSearchesParams) ([]ListTrendingSearchesRow, error) {
	rows, err := q.db.Query(ctx, listTrendingSearches, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrendingSearchesRow{}
	for rows.Next() {
		var i ListTrendingSearchesRow
		if err := rows.Scan(&i.Keyword, &i.SearchCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSearchTerm = `-- name: RecordSearchTerm :exec
INSERT INTO search_terms (keyword, search_count)
VALUES ($1, 1)
ON CONFLICT (keyword)
DO UPDATE SET
    search_count = search_terms.search_count + 1,
    last_searched_at = NOW()
`

func (q *Queries) RecordSearchTerm(ctx context.Context, keyword string) error {
	_, err := q.db.Exec(ctx, recordSearchTerm, keyword)
	return err
}

const searchPosts = `-- name: SearchPosts :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key,
    ts_rank(
        to_tsvector('simple', p.title || ' ' || p.content),
        plainto_tsquery('simple', $1)
    ) AS relevance
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
WHERE to_tsvector('simple', p.title || ' ' || p.content)
      @@ plainto_tsquery('simple', $1)
ORDER BY relevance DESC, p.created_at DESC, p.id DESC
LIMIT $3 OFFSET $2
`

type SearchPostsParams struct {
	SearchQuery string `json:"search_query"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type SearchPostsRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
	Relevance      float32     `json:"relevance"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.SearchQuery, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT id, name, description, created_at
FROM tags
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type SearchTagsParams struct {
	SearchQuery pgtype.Text `json:"search_query"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags, arg.SearchQuery, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, avatar_url, bio
FROM users
WHERE username ILIKE '%' || $1 || '%'
ORDER BY username ASC
LIMIT $3 OFFSET $2
`

type SearchUsersParams struct {
	SearchQuery pgtype.Text `json:"search_query"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type SearchUsersRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.SearchQuery, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarURL,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
