// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFollow = `-- name: AddFollow :execrows
INSERT INTO follows (
    follower_id, following_id
) VALUES (
    $1, $2
) ON CONFLICT (follower_id, following_id) DO NOTHING
`

type AddFollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) AddFollow(ctx context.Context, arg AddFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFollow, arg.FollowerID, arg.FollowingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*)::bigint FROM follows WHERE following_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*)::bigint FROM follows WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND following_id = $2
) AS following
`

type IsFollowingParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT
    u.id, u.username, u.avatar_url, u.bio
FROM follows f
JOIN users u ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFollowersParams struct {
	FollowingID uuid.UUID `json:"following_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListFollowersRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FollowingID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarURL,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
    u.id, u.username, u.avatar_url, u.bio
FROM follows f
JOIN users u ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFollowingParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListFollowingRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarURL,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFollow = `-- name: RemoveFollow :execrows
DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type RemoveFollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) RemoveFollow(ctx context.Context, arg RemoveFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFollow, arg.FollowerID, arg.FollowingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
