// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaTypeEnum string

const (
	MediaTypeEnumImage MediaTypeEnum = "image"
	MediaTypeEnumVideo MediaTypeEnum = "video"
)

func (e *MediaTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaTypeEnum(s)
	case string:
		*e = MediaTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaTypeEnum: %T", src)
	}
	return nil
}

type NullMediaTypeEnum struct {
	MediaTypeEnum MediaTypeEnum `json:"media_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if MediaTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MediaTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaTypeEnum), nil
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Collection struct {
	UserID    uuid.UUID  `json:"user_id"`
	PostID    uuid.UUID  `json:"post_id"`
	FolderID  *uuid.UUID `json:"folder_id"`
	CreatedAt time.Time  `json:"created_at"`
}

type CollectionFolder struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        uuid.UUID  `json:"id"`
	PostID    uuid.UUID  `json:"post_id"`
	UserID    uuid.UUID  `json:"user_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Content   string     `json:"content"`
	LikeCount int32      `json:"like_count"`
	CreatedAt time.Time  `json:"created_at"`
}

type Follow struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Like struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TargetID   uuid.UUID `json:"target_id"`
	TargetType int16     `json:"target_type"`
	CreatedAt  time.Time `json:"created_at"`
}

type Notification struct {
	ID               uuid.UUID          `json:"id"`
	RecipientID      uuid.UUID          `json:"recipient_id"`
	ActorID          uuid.UUID          `json:"actor_id"`
	NotificationType string             `json:"notification_type"`
	PostID           *uuid.UUID         `json:"post_id"`
	CommentID        *uuid.UUID         `json:"comment_id"`
	CreatedAt        time.Time          `json:"created_at"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
}

type Post struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	ViewCount    int64     `json:"view_count"`
	LikeCount    int64     `json:"like_count"`
	CollectCount int64     `json:"collect_count"`
	CommentCount int64     `json:"comment_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PostMedium struct {
	ID        uuid.UUID     `json:"id"`
	PostID    uuid.UUID     `json:"post_id"`
	MediaKey  string        `json:"media_key"`
	MediaType MediaTypeEnum `json:"media_type"`
	Width     int32         `json:"width"`
	Height    int32         `json:"height"`
	SortOrder int16         `json:"sort_order"`
	CreatedAt time.Time     `json:"created_at"`
}

type PostTag struct {
	PostID    uuid.UUID `json:"post_id"`
	TagID     uuid.UUID `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SearchHistory struct {
	UserID     uuid.UUID `json:"user_id"`
	Keyword    string    `json:"keyword"`
	SearchedAt time.Time `json:"searched_at"`
}

type SearchTerm struct {
	Keyword        string    `json:"keyword"`
	SearchCount    int64     `json:"search_count"`
	LastSearchedAt time.Time `json:"last_searched_at"`
}

type Tag struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Topic struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CoverURL    string    `json:"cover_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TopicPost struct {
	TopicID   uuid.UUID `json:"topic_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	AvatarURL    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	LastUsedAt       time.Time          `json:"last_used_at"`
}
