// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE recipient_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, recipientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCommentNotification = `-- name: CreateCommentNotification :exec
INSERT INTO notifications (
    id, recipient_id, actor_id, notification_type, post_id, comment_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateCommentNotificationParams struct {
	ID               uuid.UUID  `json:"id"`
	RecipientID      uuid.UUID  `json:"recipient_id"`
	ActorID          uuid.UUID  `json:"actor_id"`
	NotificationType string     `json:"notification_type"`
	PostID           *uuid.UUID `json:"post_id"`
	CommentID        *uuid.UUID `json:"comment_id"`
}

func (q *Queries) CreateCommentNotification(ctx context.Context, arg CreateCommentNotificationParams) error {
	_, err := q.db.Exec(ctx, createCommentNotification,
		arg.ID,
		arg.RecipientID,
		arg.ActorID,
		arg.NotificationType,
		arg.PostID,
		arg.CommentID,
	)
	return err
}

const createPostNotification = `-- name: CreatePostNotification :exec
INSERT INTO notifications (
    id, recipient_id, actor_id, notification_type, post_id
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreatePostNotificationParams struct {
	ID               uuid.UUID  `json:"id"`
	RecipientID      uuid.UUID  `json:"recipient_id"`
	ActorID          uuid.UUID  `json:"actor_id"`
	NotificationType string     `json:"notification_type"`
	PostID           *uuid.UUID `json:"post_id"`
}

func (q *Queries) CreatePostNotification(ctx context.Context, arg CreatePostNotificationParams) error {
	_, err := q.db.Exec(ctx, createPostNotification,
		arg.ID,
		arg.RecipientID,
		arg.ActorID,
		arg.NotificationType,
		arg.PostID,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT
    n.id, n.notification_type, n.post_id, n.comment_id,
    n.created_at, n.read_at,
    u.id AS actor_id, u.username AS actor_username, u.avatar_url AS actor_avatar
FROM notifications n
JOIN users u ON u.id = n.actor_id
WHERE n.recipient_id = $1
ORDER BY n.created_at DESC, n.id DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListNotificationsRow struct {
	ID               uuid.UUID          `json:"id"`
	NotificationType string             `json:"notification_type"`
	PostID           *uuid.UUID         `json:"post_id"`
	CommentID        *uuid.UUID         `json:"comment_id"`
	CreatedAt        time.Time          `json:"created_at"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	ActorID          uuid.UUID          `json:"actor_id"`
	ActorUsername    string             `json:"actor_username"`
	ActorAvatar      pgtype.Text        `json:"actor_avatar"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationType,
			&i.PostID,
			&i.CommentID,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ActorID,
			&i.ActorUsername,
			&i.ActorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, NOW())
WHERE id = $1 AND recipient_id = $2
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
