// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id, user_id, title, content
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, title, content, view_count, like_count, collect_count, comment_count, created_at, updated_at
`

type CreatePostParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.LikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreatePostMediaParams struct {
	ID        uuid.UUID     `json:"id"`
	PostID    uuid.UUID     `json:"post_id"`
	MediaKey  string        `json:"media_key"`
	MediaType MediaTypeEnum `json:"media_type"`
	Width     int32         `json:"width"`
	Height    int32         `json:"height"`
	SortOrder int16         `json:"sort_order"`
}

const decrementPostCollectCount = `-- name: DecrementPostCollectCount :exec
UPDATE posts SET collect_count = GREATEST(collect_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostCollectCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementPostCollectCount, id)
	return err
}

const decrementPostCommentCount = `-- name: DecrementPostCommentCount :exec
UPDATE posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementPostCommentCount, id)
	return err
}

const decrementPostLikeCount = `-- name: DecrementPostLikeCount :exec
UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementPostLikeCount, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const deletePostMediaByPostID = `-- name: DeletePostMediaByPostID :exec
DELETE FROM post_media WHERE post_id = $1
`

func (q *Queries) DeletePostMediaByPostID(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostMediaByPostID, postID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id, p.user_id, p.title, p.content, p.view_count, p.like_count,
    p.collect_count, p.comment_count, p.created_at, p.updated_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.id = $1 LIMIT 1
`

type GetPostByIDRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.LikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorAvatar,
	)
	return i, err
}

const getPostMediaByPostID = `-- name: GetPostMediaByPostID :many
SELECT id, post_id, media_key, media_type, width, height, sort_order, created_at
FROM post_media
WHERE post_id = $1
ORDER BY sort_order
`

func (q *Queries) GetPostMediaByPostID(ctx context.Context, postID uuid.UUID) ([]PostMedium, error) {
	rows, err := q.db.Query(ctx, getPostMediaByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostMedium{}
	for rows.Next() {
		var i PostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.MediaKey,
			&i.MediaType,
			&i.Width,
			&i.Height,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostCollectCount = `-- name: IncrementPostCollectCount :exec
UPDATE posts SET collect_count = collect_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostCollectCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostCollectCount, id)
	return err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostCommentCount, id)
	return err
}

const incrementPostLikeCount = `-- name: IncrementPostLikeCount :exec
UPDATE posts SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostLikeCount, id)
	return err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
WHERE p.user_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListPostsByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListPostsByUserRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]ListPostsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPostsByUser, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByUserRow{}
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFeed = `-- name: ListPostsFeed :many
SELECT
    p.id, p.title, p.content, p.view_count, p.like_count, p.collect_count,
    p.comment_count, p.created_at,
    u.id AS author_id, u.username AS author_username, u.avatar_url AS author_avatar,
    COALESCE(pm.media_key, '') AS cover_key
FROM (
    SELECT id, user_id, title, content, view_count, like_count, collect_count,
           comment_count, created_at
    FROM posts
    ORDER BY id DESC
    LIMIT $2 OFFSET $1
) p
JOIN users u ON p.user_id = u.id
LEFT JOIN LATERAL (
    SELECT media_key
    FROM post_media
    WHERE post_id = p.id
    ORDER BY sort_order ASC
    LIMIT 1
) pm ON true
ORDER BY p.id DESC
`

type ListPostsFeedParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

type ListPostsFeedRow struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	ViewCount      int64       `json:"view_count"`
	LikeCount      int64       `json:"like_count"`
	CollectCount   int64       `json:"collect_count"`
	CommentCount   int64       `json:"comment_count"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorID       uuid.UUID   `json:"author_id"`
	AuthorUsername string      `json:"author_username"`
	AuthorAvatar   pgtype.Text `json:"author_avatar"`
	CoverKey       string      `json:"cover_key"`
}

func (q *Queries) ListPostsFeed(ctx context.Context, arg ListPostsFeedParams) ([]ListPostsFeedRow, error) {
	rows, err := q.db.Query(ctx, listPostsFeed, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsFeedRow{}
	for rows.Next() {
		var i ListPostsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.LikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.CoverKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $1, content = $2, updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, title, content, view_count, like_count, collect_count, comment_count, created_at, updated_at
`

type UpdatePostParams struct {
	Title   string    `json:"title"`
	Content string    `json:"content"`
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.LikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
