// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCollection(ctx context.Context, arg AddCollectionParams) (int64, error)
	AddCommentLike(ctx context.Context, arg AddCommentLikeParams) (int64, error)
	AddFollow(ctx context.Context, arg AddFollowParams) (int64, error)
	AddPostLike(ctx context.Context, arg AddPostLikeParams) (int64, error)
	AddPostTag(ctx context.Context, arg AddPostTagParams) (int64, error)
	AddSearchHistory(ctx context.Context, arg AddSearchHistoryParams) error
	CountCollectionFolderPosts(ctx context.Context, arg CountCollectionFolderPostsParams) (int64, error)
	CountCollectionFolders(ctx context.Context, userID uuid.UUID) (int64, error)
	CountCollections(ctx context.Context, userID uuid.UUID) (int64, error)
	CountCommentsByPostID(ctx context.Context, postID uuid.UUID) (int64, error)
	CountFollowers(ctx context.Context, followingID uuid.UUID) (int64, error)
	CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountFollowingPosts(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLikedPosts(ctx context.Context, userID uuid.UUID) (int64, error)
	CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountPostsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPostsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPostsFeed(ctx context.Context) (int64, error)
	CountReceivedLikeAndCollectByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountRecommendedPosts(ctx context.Context) (int64, error)
	CountSearchHistory(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSearchPosts(ctx context.Context, searchQuery string) (int64, error)
	CountSearchTags(ctx context.Context, searchQuery pgtype.Text) (int64, error)
	CountSearchUsers(ctx context.Context, searchQuery pgtype.Text) (int64, error)
	CountTagPosts(ctx context.Context, tagID uuid.UUID) (int64, error)
	CountTopicPosts(ctx context.Context, topicID uuid.UUID) (int64, error)
	CountTopics(ctx context.Context) (int64, error)
	CountTrendingSearches(ctx context.Context) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateCollectionFolder(ctx context.Context, arg CreateCollectionFolderParams) (CollectionFolder, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateCommentNotification(ctx context.Context, arg CreateCommentNotificationParams) error
	CreateFollowNotification(ctx context.Context, arg CreateFollowNotificationParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostMedia(ctx context.Context, arg []CreatePostMediaParams) (int64, error)
	CreatePostNotification(ctx context.Context, arg CreatePostNotificationParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementCommentLikeCount(ctx context.Context, id uuid.UUID) error
	DecrementPostCollectCount(ctx context.Context, id uuid.UUID) error
	DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	DecrementPostLikeCount(ctx context.Context, id uuid.UUID) error
	DeleteCollectionFolder(ctx context.Context, arg DeleteCollectionFolderParams) (int64, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error)
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeletePostMediaByPostID(ctx context.Context, postID uuid.UUID) error
	DeletePostTags(ctx context.Context, postID uuid.UUID) error
	DeleteSearchHistory(ctx context.Context, userID uuid.UUID) error
	GetActiveAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetCollectionFolderByID(ctx context.Context, arg GetCollectionFolderByIDParams) (CollectionFolder, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetFollowerCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetFollowingCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error)
	GetPostMediaByPostID(ctx context.Context, postID uuid.UUID) ([]PostMedium, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementCommentLikeCount(ctx context.Context, id uuid.UUID) error
	IncrementPostCollectCount(ctx context.Context, id uuid.UUID) error
	IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	IncrementPostLikeCount(ctx context.Context, id uuid.UUID) error
	IncrementViewCount(ctx context.Context, id uuid.UUID) error
	IsCollected(ctx context.Context, arg IsCollectedParams) (bool, error)
	IsCommentLiked(ctx context.Context, arg IsCommentLikedParams) (bool, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	IsPostLiked(ctx context.Context, arg IsPostLikedParams) (bool, error)
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListCollectionFolderPosts(ctx context.Context, arg ListCollectionFolderPostsParams) ([]ListCollectionFolderPostsRow, error)
	ListCollectionFolders(ctx context.Context, arg ListCollectionFoldersParams) ([]CollectionFolder, error)
	ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error)
	ListCommentsByPostID(ctx context.Context, arg ListCommentsByPostIDParams) ([]ListCommentsByPostIDRow, error)
	ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error)
	ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error)
	ListFollowingPosts(ctx context.Context, arg ListFollowingPostsParams) ([]ListFollowingPostsRow, error)
	ListLikedPosts(ctx context.Context, arg ListLikedPostsParams) ([]ListLikedPostsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]ListPostsByUserRow, error)
	ListPostsFeed(ctx context.Context, arg ListPostsFeedParams) ([]ListPostsFeedRow, error)
	ListRecommendedPosts(ctx context.Context, arg ListRecommendedPostsParams) ([]ListRecommendedPostsRow, error)
	ListSearchHistory(ctx context.Context, arg ListSearchHistoryParams) ([]ListSearchHistoryRow, error)
	ListTagPosts(ctx context.Context, arg ListTagPostsParams) ([]ListTagPostsRow, error)
	ListTagsByPostID(ctx context.Context, postID uuid.UUID) ([]Tag, error)
	ListTopicPosts(ctx context.Context, arg ListTopicPostsParams) ([]ListTopicPostsRow, error)
	ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error)
	ListTrendingSearches(ctx context.Context, arg ListTrendingSearchesParams) ([]ListTrendingSearchesRow, error)
	MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	RecalculatePostCommentCount(ctx context.Context, postID uuid.UUID) error
	RecordSearchTerm(ctx context.Context, keyword string) error
	RemoveCollection(ctx context.Context, arg RemoveCollectionParams) (int64, error)
	RemoveCommentLike(ctx context.Context, arg RemoveCommentLikeParams) (int64, error)
	RemoveFollow(ctx context.Context, arg RemoveFollowParams) (int64, error)
	RemovePostLike(ctx context.Context, arg RemovePostLikeParams) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateCollectionFolder(ctx context.Context, arg UpdateCollectionFolderParams) (CollectionFolder, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
