// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const countPostsByUser = `-- name: CountPostsByUser :one
SELECT COUNT(*)::bigint FROM posts WHERE user_id = $1
`

func (q *Queries) CountPostsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countReceivedLikeAndCollectByUser = `-- name: CountReceivedLikeAndCollectByUser :one
SELECT
    ((SELECT COUNT(*)::bigint
      FROM likes l
      JOIN posts p ON p.id = l.target_id
      WHERE p.user_id = $1 AND l.target_type = 1)
     +
     (SELECT COUNT(*)::bigint
      FROM collections c
      JOIN posts p ON p.id = c.post_id
      WHERE p.user_id = $1))::bigint
`

func (q *Queries) CountReceivedLikeAndCollectByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReceivedLikeAndCollectByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    id, user_id, refresh_token_hash, expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, refresh_token_hash, expires_at, revoked_at, created_at, last_used_at
`

type CreateSessionParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, username, password_hash, avatar_url, bio
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, username, password_hash, avatar_url, bio, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	AvatarURL    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.AvatarURL,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at, created_at, last_used_at FROM user_sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, avatar_url, bio, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, avatar_url, bio, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET username = $1, avatar_url = $2, bio = $3, updated_at = NOW() WHERE id = $4 RETURNING id, username, password_hash, avatar_url, bio, created_at, updated_at
`

type UpdateUserParams struct {
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.AvatarURL,
		arg.Bio,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $1, updated_at = NOW() WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
