// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: viewer_state.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listViewerCommentLikedStates = `-- name: ListViewerCommentLikedStates :many
SELECT
    c.id AS comment_id,
    EXISTS(
        SELECT 1 FROM likes l
        WHERE l.user_id = $1 AND l.target_id = c.id AND l.target_type = 2
    ) AS viewer_liked
FROM comments c
WHERE c.id = ANY($2::uuid[])
`

type ListViewerCommentLikedStatesParams struct {
	ViewerID   uuid.UUID   `json:"viewer_id"`
	CommentIds []uuid.UUID `json:"comment_ids"`
}

type ListViewerCommentLikedStatesRow struct {
	CommentID   uuid.UUID `json:"comment_id"`
	ViewerLiked bool      `json:"viewer_liked"`
}

func (q *Queries) ListViewerCommentLikedStates(ctx context.Context, arg ListViewerCommentLikedStatesParams) ([]ListViewerCommentLikedStatesRow, error) {
	rows, err := q.db.Query(ctx, listViewerCommentLikedStates, arg.ViewerID, arg.CommentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViewerCommentLikedStatesRow{}
	for rows.Next() {
		var i ListViewerCommentLikedStatesRow
		if err := rows.Scan(&i.CommentID, &i.ViewerLiked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewerFollowingStates = `-- name: ListViewerFollowingStates :many
SELECT
    u.id AS user_id,
    EXISTS(
        SELECT 1 FROM follows f
        WHERE f.follower_id = $1 AND f.following_id = u.id
    ) AS viewer_following
FROM users u
WHERE u.id = ANY($2::uuid[])
`

type ListViewerFollowingStatesParams struct {
	ViewerID uuid.UUID   `json:"viewer_id"`
	UserIds  []uuid.UUID `json:"user_ids"`
}

type ListViewerFollowingStatesRow struct {
	UserID          uuid.UUID `json:"user_id"`
	ViewerFollowing bool      `json:"viewer_following"`
}

func (q *Queries) ListViewerFollowingStates(ctx context.Context, arg ListViewerFollowingStatesParams) ([]ListViewerFollowingStatesRow, error) {
	rows, err := q.db.Query(ctx, listViewerFollowingStates, arg.ViewerID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViewerFollowingStatesRow{}
	for rows.Next() {
		var i ListViewerFollowingStatesRow
		if err := rows.Scan(&i.UserID, &i.ViewerFollowing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewerPostStates = `-- name: ListViewerPostStates :many
SELECT
    p.id AS post_id,
    EXISTS(
        SELECT 1 FROM likes l
        WHERE l.user_id = $1 AND l.target_id = p.id AND l.target_type = 1
    ) AS viewer_liked,
    EXISTS(
        SELECT 1 FROM collections c
        WHERE c.user_id = $1 AND c.post_id = p.id
    ) AS viewer_collected,
    EXISTS(
        SELECT 1 FROM follows f
        WHERE f.follower_id = $1 AND f.following_id = p.user_id
    ) AS viewer_following
FROM posts p
WHERE p.id = ANY($2::uuid[])
`

type ListViewerPostStatesParams struct {
	ViewerID uuid.UUID   `json:"viewer_id"`
	PostIds  []uuid.UUID `json:"post_ids"`
}

type ListViewerPostStatesRow struct {
	PostID          uuid.UUID `json:"post_id"`
	ViewerLiked     bool      `json:"viewer_liked"`
	ViewerCollected bool      `json:"viewer_collected"`
	ViewerFollowing bool      `json:"viewer_following"`
}

func (q *Queries) ListViewerPostStates(ctx context.Context, arg ListViewerPostStatesParams) ([]ListViewerPostStatesRow, error) {
	rows, err := q.db.Query(ctx, listViewerPostStates, arg.ViewerID, arg.PostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViewerPostStatesRow{}
	for rows.Next() {
		var i ListViewerPostStatesRow
		if err := rows.Scan(
			&i.PostID,
			&i.ViewerLiked,
			&i.ViewerCollected,
			&i.ViewerFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
